name: CI/CD Pipeline for OpenShift

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment (adjust if you're using other languages or tools)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19' 
          
      # Step 3: Install dependencies and build the app
      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      # Step 4: Log in to OpenShift using the OpenShift token and server URL
      - name: Log in to OpenShift
        run: |
          oc login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER }}

      # Step 5: Set OpenShift Project (replace with your actual project name)
      - name: Set OpenShift Project
        run: |
          oc project india-dev  # Replace with your OpenShift project name

      # Step 6: Deploy to OpenShift
      - name: Deploy to OpenShift
        run: |
          oc apply -f cms-karma-kebab.yaml --force # Replace with your OpenShift deployment YAML file