name: CI/CD Pipeline for OpenShift

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Log in to OpenShift using the OpenShift token and server URL
      - name: Log in to OpenShift
        run: |
          oc login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER }}

      # Step 3: Set OpenShift Project (replace with your actual project name)
      - name: Set OpenShift Project
        run: |
          oc project india-dev  # Replace with your OpenShift project name

      # Step 4: Trigger OpenShift Build (this will use BuildConfig defined above)
      - name: Start OpenShift Build
        run: |
          oc start-build cms-karma-kebab --wait  # Trigger the build and wait for completion

      # Step 5: Deploy to OpenShift (use the generated image from the build)
      - name: Deploy to OpenShift
        run: |
          oc apply -f cms-karma-kebab.yaml --force  # Deploy the application to OpenShift with the new image
